# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Build Dis Chat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Build Dis Chat

  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

end
